#!/bin/sh
# Switch to a visible workspace (chosen via rofi).

ws=$($HOME/.cargo/bin/swayg workspace list --visible --plain 2>/dev/null | rofi -dmenu -p "Switch to:")
if [ -n "$ws" ]; then
    $HOME/.cargo/bin/swayg nav go "$ws"
fi
