#!/bin/sh
# Switch active group via rofi.
# Output is auto-resolved from group state.
# Entering a new name creates the group.

group=$($HOME/.cargo/bin/swayg group list | awk '/^Group/{sub(/^Group "/,""); sub(/":$/,""); print}' | rofi -dmenu -p "Select group:")
if [ -z "$group" ]; then
    exit 0
fi

$HOME/.cargo/bin/swayg group select "$group" --create
